app/models.py
from . import db

class Project(db.Model):
    __tableName_ = "Project"
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(64))
    version = db.Column(db.String(64))
    description = db.Column(db.Text())
    android_jenkins_url = db.Column(db.String(64))
    ios_jenkins_url = db.Column(db.String(64))
    plist_name = db.Column(db.String(64))
    plist_url = db.Column(db.String(64))

    def __repr__(self):
        return "<Project %r>"%self.name
        

app/__init__.py
from config import config
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_uploads import UploadSet,configure_uploads
from werkzeug.contrib.fixers import ProxyFix

db = SQLAlchemy()
store = UploadSet("store")

def create_app(config_name):
    app = Flask(__name__)
    app.config.from_object(config[config_name])
    config[config_name].init_app(app)
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)
    db.init_app(app)
    configure_uploads(app,store)
    # Set up for nginx if using proxy server when deployment
    app.wsgi_app = ProxyFix(app.wsgi_app)
    return app

app/main/__init__.py
from flask import Blueprint

main = Blueprint("main",__name__)
from . import views

app/main/views.py
from flask import render_template, send_from_directory, request, jsonify, redirect, url_for, make_response, send_file, current_app
from .form import ProjectForm
from ..models import Project
from .. import db, store
from . import main
import os, time, shutil, glob, subprocess
from subprocess import call
import threading
from flask_httpauth import HTTPBasicAuth

auth = HTTPBasicAuth()
users = [{"username":"admin","password":"test"}]
@auth.get_password
def get_password(username):
    for user in users:
        if user["username"]== username:
            return user["password"]
    return None

@main.route("/", methods=["GET","POST"])
def index():
    showLink = {"showIpaLink":True,"showAndroidLink":True,"showiOSLink":True}
    userAgent = request.headers.get("User-Agent")
    if any(agent in userAgent for agent in ["iPhone","iPad"]):
        showLink["showIpaLink"] = False
        showLink["showAndroidLink"] = False
    elif "Android" in userAgent:
        showLink["showIpaLink"] = False
        showLink["showiOSLink"] = False
    projectList = Project.query.all()
    # Append app latest update time
    for project in projectList:
        folderName = "%s-%s"%(project.name,project.version)
        directory =os.path.join(current_app.config["UPLOADED_STORE_DEST"] ,folderName) 

        for file in os.listdir(directory):
            if file.endswith(".ipa"):
                setattr(project, "iOSUpdateTime",time.ctime(os.path.getmtime(os.path.join(directory,file))))
            elif file.endswith(".apk"):
                setattr(project, "androidUpdateTime",time.ctime(os.path.getmtime(os.path.join(directory,file))))
        if not hasattr(project,"iOSUpdateTime"):
            setattr(project, "iOSUpdateTime",None)
        if not hasattr(project,"androidUpdateTime"):
            setattr(project, "androidUpdateTime",None)
    return render_template('index.html', projectList=projectList, showLink=showLink)
    
@main.route("/installCA", methods=["GET","POST"])
def installCA():
    print(current_app.config["UPLOADED_STORE_DEST"])
    return send_from_directory(current_app.config["UPLOADED_STORE_DEST"], "ca.crt", as_attachment=True)

@main.route("/admin", methods=["GET","POST"])
@auth.login_required
def admin():
    form = ProjectForm()
    projectList = Project.query.all()
    return render_template("admin.html",projectList=projectList)

@main.route("/testSync", methods=["GET","POST"])
def testSync():
    form = ProjectForm()
    projectList = Project.query.all()
    return render_template("test.html",projectList=projectList)

@main.route("/createProject", methods=["GET","POST"])
def createProject():
    form = ProjectForm()
    form.getProjectID(request.form.get("id",0))
    if form.validate_on_submit():
        id = int(request.form["id"]) 
        plist_name = ""
        plist_url = ""
        folderName = "%s-%s"%(form.name.data,form.version.data)
        if form.plist.data:
            plist_name = store.save(form.plist.data, name ="%s/"%folderName +  folderName + "." )
            plist_url = store.url(plist_name)
        if id==0:
            project = Project(name=form.name.data, version=form.version.data, description=form.description.data, android_jenkins_url=form.android_jenkins_url.data,ios_jenkins_url=form.ios_jenkins_url.data, plist_name=plist_name, plist_url=plist_url)
        else:
            project = Project.query.get_or_404(id)
            project.name = form.name.data
            project.version = form.version.data
            project.description = form.description.data
            project.android_jenkins_url = form.android_jenkins_url.data
            project.ios_jenkins_url = form.ios_jenkins_url.data
            project.plist_name=plist_name
            project.plist_url =plist_url
        #create related folder
        try:
            directory =os.path.join(current_app.config["UPLOADED_STORE_DEST"] ,folderName) 
            if not os.path.exists(directory):
                os.makedirs(directory)
        except OSError:
            print ('Error: Creating directory. ' +  directory)
        db.session.add(project)
        return jsonify(status='ok')
    if int(request.args.get("id",0)) != 0 or int(request.form.get("id",0)) != 0:
        projectID = request.args.get("id",0) if  request.args.get("id",0) else request.form.get("id",0)
        project = Project.query.get_or_404(int(projectID))
        form.name.data = project.name
        form.version.data = project.version
        form.description.data = project.description
        form.android_jenkins_url.data = project.android_jenkins_url
        form.ios_jenkins_url.data = project.ios_jenkins_url
        return render_template("project.html",form=form,projectID=project.id)
    else:
        return render_template("project.html",form=form)

@main.route("/deleteProject", methods=["GET","POST"])
def deleteProject():
    if request.method == 'POST':
        print(request.args.get("id"))
        project = Project.query.get_or_404(int(request.form["id"]))
        db.session.delete(project)
        #delete related folder
        folderName = "%s-%s"%(project.name,project.version)
        directory =os.path.join(current_app.config["UPLOADED_STORE_DEST"] ,folderName) 
        if os.path.exists(directory):
            shutil.rmtree(directory)
        return jsonify(status='ok')

@main.route("/download", methods=["GET","POST"])
def download():
    project = Project.query.get_or_404(request.args.get("projectID"))
    folderName = "%s-%s"%(project.name,project.version)
    directory =os.path.join(current_app.config["UPLOADED_STORE_DEST"] ,folderName) 
    type = request.args.get("type")
    for file in os.listdir(directory):
        if file.endswith(".ipa") and type == "ipa":
            filename = file
            break
        elif file.endswith(".apk") and type == "apk":
            filename = file
            break
        elif type == "iOS":
            return "itms-services://?action=download-manifest&url=https://127.0.0.1:5000/static/anwstream.plist"
        else:
            filename = None
    return send_from_directory(directory, filename, as_attachment=True)


@main.route("/sync", methods=["GET","POST"])
def sync():
    print("start sync")
    t = threading.Thread(target=startTask, args=[current_app._get_current_object()])
    t.daemon = True
    t.start()
    print("return sync status")
    return jsonify(status='ok')

@main.route("/getIPA", methods=["GET","POST"])
def getIPA():
    response = make_response(send_file("anwstream.ipa"))
    response.headers["Content-Disposition"] = "attachment;filename=anwstream.ipa;"
    return response

@main.route("/downloadPlistTemplate", methods=["GET","POST"])
def downloadPlistTemplate():
    return send_from_directory(current_app.config["UPLOADED_STORE_DEST"], "template.plist", as_attachment=True)

def startTask(app):
    with app.app_context():
        directory =os.path.join(current_app.config["UPLOADED_STORE_DEST"] ,"TestApp-master")  
        print("cd %s && node %s "%(directory,"upgradePOCStream.js"))
        process=subprocess.Popen("cd %s && node %s "%(directory,"upgradePOCStream.js"),stdout=subprocess.PIPE, shell=True)
        while True:
            output = process.stdout.readline().decode('utf-8')
            if output != '':
                print(output.strip())
     

app/templates/admin.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>App Store Admin</title>
    <link rel="shortcut icon" href="{{ url_for('static', filename = 'favicon.png') }}" type="image/x-icon">
    <link rel="icon" href="{{ url_for('static', filename = 'favicon.png') }}" type="image/x-icon">
    <link rel="stylesheet" type="text/css" href="static/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="static/css/custom.css">
    <script defer src="/static/js/fontawesome-all.min.js"></script>

</head>

<body>
    <div class="admin container">
        <div class="card">
            <div class="card-header">
                <div class="row">
                    <div class="col col-xs-6">
                        <h5>Mobile App Project</h5>
                    </div>
                    <div class="col col-xs-6 text-right">
                        <button id="createProject" class="btn btn-sm btn-primary createApp" data-toggle="modal" data-target="#exampleModalCenter">
                            <i class="far fa-plus-square fa-lg"></i>
                        </button>
                    </div>
                </div>
            </div>
            <div class="table-responsive card-body">
                <table class="table table-bordered">
                    <thead>
                        <tr class="text-center">
                            <th>Name</th>
                            <th>Version</th>
                            <th>Descirption</th>
                            <th>Android Jenkins Url</th>
                            <th>iOS Jenkins Url</th>         
                            <th>
                                <em class="fa fa-cog"></em>
                            </th>
                            <th>
                                <i class="fas fa-eye"></i>                                    
                            </th>
                        </tr>
                    </thead>
                    <tbody class="text-center">
                        {% for project in projectList %}
                        <tr>
                            <td class="hidden-xs">{{project.name}}</td>
                            <td>{{project.version}}</td>
                            <td>{{project.description}}</td>
                            <td>{{project.android_jenkins_url}}</td>
                            <td>{{project.ios_jenkins_url}}</td>
                            
                            <td>
                                <a class="editProject"  data-toggle="tooltip" data-placement="bottom" title="edit" data-id="{{project.id}}">
                                    <i class="far fa-edit" ></i>
                                </a>
                                <span data-toggle="modal" data-target="#deleteModal"  data-id="{{project.id}}" data-name="{{project.name}}" data-version="{{project.version}}">
                                    <a class="deleteProject" data-toggle="tooltip" data-placement="bottom" title="delete" >
                                        <i class="far fa-trash-alt"></i>
                                    </a>
                                </span>
                                <a class="sync" data-toggle="tooltip" data-placement="bottom" title="sync">
                                    <i class="far fa-play-circle"></i>
                                </a>
                            </td>
                            <td class="executionSection">

                            </td>
                        </tr>
                        {% endfor %}

                    </tbody>
                </table>
            </div>
        </div>


        <!-- Modal-create -->
        <div class="create modal fade" id="createModal" tabindex="-1" role="dialog" aria-labelledby="createModal" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered" role="document">
                <div class="modal-content">


                </div>
            </div>
        </div>

        <!-- Modal-delete -->
        <div class="delete modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModal" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Delete</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                  </button>
                    </div>
                    <div class="modal-body">
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">No</button>
                        <button type="button" class="yes btn btn-primary" data-id="">Yes</button>
                    </div>
                </div>
            </div>
        </div>

    </div>

    <script src="static/js/jquery-3.2.1.min.js"></script>
    <script src="static/js/popper.min.js"></script>
    <script src="static/js/bootstrap.min.js"></script>
    <script>
        function check(id) {
            var url = "{{ url_for('main.createProject') }}";
            var formData = new FormData($('#project')[0]);
            formData.append("id",id)
            $.ajax({
                url: url,
                type: 'POST',
                cache: false,
                data: formData,
                processData: false,
                contentType: false,
                success:function(data) {    
                    if (data.status == 'ok') {
                        $('.create.modal').modal('hide');
                        location.href = "{{ url_for('main.admin') }}";
                    }
                    else {
                        $('.create.modal').find(".modal-content").html(data);

                    }
                }
            });
        };

        $(".delete.modal").on("show.bs.modal", function (event) {
            var delButton = $(event.relatedTarget);
            id = delButton.data("id");
            name = delButton.data("name");
            version = delButton.data("version");
            delButton.data("id");
            var modal = $(this);
            modal.find('.modal-body').text('Are you sure to delete project ' + name + " " + version + "?")
            modal.find(".yes.btn").data("id", id);
            $(".yes.btn").on("click", function() {
                var projectID = $(this).data('id');
                var url = "{{url_for('main.deleteProject')}}";
                $.post(url, data = { id: projectID }, function (data) {
                    if (data.status == 'ok') {
                        $("delete.modal").modal("hide");
                        location.href = "{{ url_for('main.admin') }}";
                    };
                });

            });

        });

        $(".create.modal").on("shown.bs.modal", function (event) {
              $('[data-toggle="tooltip"]').tooltip();
        });

        $(document).ready(function () {
            $('[data-toggle="tooltip"]').tooltip();

            $('#createProject').click(function () {
                var url = "{{ url_for('main.createProject') }}";
                $.get(url, function (data) {
                    $('.create.modal').find(".modal-content").html(data);
                    $('.create.modal').modal();
                });
            });

            $(".editProject").each(function () {
                $(this).on('click', function () {
                    project_id = $(this).attr("data-id");
                    var url = "{{ url_for('main.createProject') }}";
                    $.get(url, { "id": project_id }, function (data) {
                        $('.create.modal').find(".modal-content").html(data);
                        $('.create.modal').modal();

                    });
                });
            });

            $(".sync").each(function () {
                $(this).on("click",function(event){
                    var syncElem = $(this);
                    var url = "{{url_for('main.sync')}}";
                    $.get(url,function(data){
                        if (data.status == 'ok') {
                            var progressEelem = syncElem.parent().next(".executionSection").find(".progress");
                            progressEelem.remove();
                            syncElem.parent().next(".executionSection").append('<span class="executionStatus" style="margin-right:5px"><i class="far fa-check-circle"></i></span><a href="#" ><i class="far fa-file-alt"></i></a>')
                        };

                    });
                    if ($(this).parent().next(".executionSection").find(".executionStatus").length){
                        $(this).parent().next(".executionSection").empty()
                    }
                    html = '<div class="progress"> <div class="progress-bar progress-bar-striped progress-bar-animated" role="progressbar" aria-valuenow="75" aria-valuemin="0" aria-valuemax="100" style="width:0%"></div></div>'
                    $(this).parent().next(".executionSection").append(html);
                    var progressBarEelem = $(this).parent().next(".executionSection").find(".progress-bar"); 
                    var width = 0;
                    var id = setInterval(frame, 1000);
                    function frame() {
                        if (width >= 100) {
                            clearInterval(id);
                        } else {
                            width = width + 10; 
                            progressBarEelem.css("width",width + '%'); 
                        }
                    }
                });
            });
               
               
           

        });
    </script>

</body>

</html>

app/templates/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>App Store</title>
    <link rel="shortcut icon" href="{{ url_for('static', filename = 'favicon.png') }}" type="image/x-icon">
    <link rel="icon" href="{{ url_for('static', filename = 'favicon.png') }}" type="image/x-icon">
    <link rel="stylesheet" type="text/css" href="static/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="static/css/custom.css">
</head>

<body>
    <div class="container-fluid">
        <blockquote class="title blockquote text-center mb-5">
            <h2 class="mt-3">Internal App Store</h2>
            <footer class="blockquote-footer">
                <cite title="Source Title">Download/Install android and iOS app in your mobile device</cite>

            </footer>
            <a href="{{url_for('main.installCA')}}" class="badge badge-primary">Install CA</a>


        </blockquote>
        {% for projectSection in projectList %}
        <div class="card text-white bg-dark mb-3">
            <div class="card-header text-center">{{projectSection.name}}-{{projectSection.version}}</div>
            <div class="card-body">
                <img class="app-icon img-thumbnail rounded float-left mr-3" src="static/images/app-icon.png" alt="Card image cap">
                <p class="card-text updateTime iOS">{% if projectSection.iOSUpdateTime %}iOS last updated time: {{projectSection.iOSUpdateTime}} {% endif %}</p>
                <p class="card-text updateTime Android">{% if projectSection.androidUpdateTime %}Android last updated time: {{projectSection.androidUpdateTime}} {% endif %}</p>
                <div class="linkSection">
                    {% if showLink["showiOSLink"] %}
                        <a href='itms-services://?action=download-manifest&url={{projectSection.plist_url}}' class="ipa btn btn-primary  ml-1 btn-sm">iOS</a>
                    {% endif%} 
                    {% if showLink["showAndroidLink"] %}
                        <a href="{{url_for('main.download',projectID=projectSection.id,type='apk')}}" class="android btn btn-primary  ml-1 btn-sm">Android</a>
                    {% endif%}
                    {% if showLink["showIpaLink"]  %}
                        <a href="{{url_for('main.download',projectID=projectSection.id,type='ipa')}}" class="iOS btn btn-primary  ml-1 btn-sm">ipa</a>
                    {% endif%}
                </div>

            </div>
        </div>
        {% endfor %}
    </div>
    <script src="static/js/jquery-3.2.1.min.js"></script>
    <script src="static/js/popper.min.js"></script>
    <script src="static/js/bootstrap.min.js"></script>
    <script>
        if (navigator.userAgent.includes("iPhone") || navigator.userAgent.includes("iPad")){
            $('.updateTime.Android').remove();
        }
        else if (navigator.userAgent.includes("Android"))
        {
            $('.updateTime.iOS').remove();
        }
    </script>
</body>

</html>

app/templates/project.html
{% from "utils/_formHelper.html" import render_field with context %}

<form id="project"  method="POST" enctype="multipart/form-data" onsubmit="return false;">            
    <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLongTitle">{% if form.name.data %}Edit {% else %}Create {% endif %}Mobile App Project</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <div class="modal-body">
                {{ form.hidden_tag() }}
                {{render_field(form.name,tooltip="Test Name")}}
                {{render_field(form.version)}} 
                {{render_field(form.description)}} 
                {{render_field(form.android_jenkins_url)}}
                {{render_field(form.ios_jenkins_url)}}
                {{render_field(form.plist,template=True)}}
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button id="createSubmit" class="btn btn-primary" onclick="{% if projectID %}check({{projectID}}){% else %}check(0){% endif %}">Save</button>
                </div>
        </div>
</form>

app/templates/test.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>App Store Test</title>
    <link rel="shortcut icon" href="{{ url_for('static', filename = 'favicon.png') }}" type="image/x-icon">
    <link rel="icon" href="{{ url_for('static', filename = 'favicon.png') }}" type="image/x-icon">
    <link rel="stylesheet" type="text/css" href="static/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="static/css/custom.css">
    <script defer src="/static/js/fontawesome-all.min.js"></script>

</head>

<body>
    <div class="admin container">
        <div class="card">
            <div class="card-header">
                <div class="row">
                    <div class="col col-xs-6">
                        <h5>Test Case Execution</h5>
                    </div>
                    <div class="col col-xs-6 text-right">
                        <button id="createProject" class="btn btn-sm btn-primary createApp" data-toggle="modal" data-target="#exampleModalCenter">
                            <i class="far fa-plus-square fa-lg"></i>
                        </button>
                    </div>
                </div>
            </div>
            <div class="table-responsive card-body">
                <table class="table table-bordered">
                    <thead>
                        <tr class="text-center">
                            <th>Name</th>
                            <th>Version</th>
                            <th>Descirption</th>
                            <th>Android Jenkins Url</th>
                            <th>iOS Jenkins Url</th>         
                            <th>
                                <em class="fa fa-cog"></em>
                            </th>
                            <th>
                                <i class="fas fa-eye"></i>                                    
                            </th>
                        </tr>
                    </thead>
                    <tbody class="text-center">
                        {% for project in projectList %}
                        <tr>
                            <td class="hidden-xs">{{project.name}}</td>
                            <td>{{project.version}}</td>
                            <td>{{project.description}}</td>
                            <td>{{project.android_jenkins_url}}</td>
                            <td>{{project.ios_jenkins_url}}</td>
                            
                            <td>
                                <a class="editProject"  data-toggle="tooltip" data-placement="bottom" title="edit" data-id="{{project.id}}">
                                    <i class="far fa-edit" ></i>
                                </a>
                                <span data-toggle="modal" data-target="#deleteModal"  data-id="{{project.id}}" data-name="{{project.name}}" data-version="{{project.version}}">
                                    <a class="deleteProject" data-toggle="tooltip" data-placement="bottom" title="delete" >
                                        <i class="far fa-trash-alt"></i>
                                    </a>
                                </span>
                                <a class="sync" data-toggle="tooltip" data-placement="bottom" title="sync">
                                    <i class="far fa-play-circle"></i>
                                </a>
                                                                
                            </td>
                            <td class="executionSection">

                            </td>

                        </tr>
                        {% endfor %}

                    </tbody>
                </table>
            </div>
        </div>


  
    <script src="static/js/jquery-3.2.1.min.js"></script>
    <script src="static/js/popper.min.js"></script>
    <script src="static/js/bootstrap.min.js"></script>
    <script>
    
        $(document).ready(function () {
            $('[data-toggle="tooltip"]').tooltip();

           

            $(".sync").each(function () {
                $(this).on("click",function(event){
                    var syncElem = $(this);
                    var url = "{{url_for('main.sync')}}";
                    $.get(url,function(data){
                        if (data.status == 'ok') {
                            var progressEelem = syncElem.parent().next(".executionSection").find(".progress");
                            progressEelem.remove();
                            syncElem.parent().next(".executionSection").append('<span class="executionStatus" style="margin-right:5px"><i class="far fa-check-circle"></i></span><a href="#" ><i class="far fa-file-alt"></i></a>')
                        };

                    });
                    if ($(this).parent().next(".executionSection").find(".executionStatus").length){
                        $(this).parent().next(".executionSection").empty()
                    }
                    html = '<div class="progress"> <div class="progress-bar progress-bar-striped progress-bar-animated" role="progressbar" aria-valuenow="75" aria-valuemin="0" aria-valuemax="100" style="width:0%"></div></div>'
                    $(this).parent().next(".executionSection").append(html);
                    var progressBarEelem = $(this).parent().next(".executionSection").find(".progress-bar"); 
                    var width = 0;
                    var id = setInterval(frame, 1000);
                    function frame() {
                        if (width >= 100) {
                            clearInterval(id);
                        } else {
                            width = width + 10; 
                            progressBarEelem.css("width",width + '%'); 
                        }
                    }
                });
            });
               
           

        });
    </script>

</body>

</html>

app/templates/utils/_formHelper.html
{% macro render_field(field) %}
    <div class="form-group">
        <label class="col-form-label">{{field.label}}</label>
        {% if kwargs.get('template',None) %}
            <a href="{{url_for('main.downloadPlistTemplate')}}"><i class="far fa-file-code"></i></a>
        {% endif %}
        {% if kwargs.get('tooltip',None) %}
                <i class="fa fa-question-circle" data-toggle="tooltip" data-placement="right" title="{{kwargs.get('tooltip',None)}}" aria-hidden="true"></i>
        {% endif %}
        {% if field.errors %}
            {{field(class="form-control is-invalid",**kwargs)}}
        {% else %}
            {{field(class="form-control",**kwargs)}}

        {% endif %}
        <div class="invalid-feedback">
            {{field.errors[0]}}
        </div>
    </div>

{% endmacro %}